### ISSUE TITLE
schroederdennis.de on List - Remove it, now!

### ISSUE THREAD

**Issue by ipv64net** [RPiList/specials#1383] opened 2023-12-17 15:37 UTC
It's getting on my nerves. "schroederdennis.de" is not malware... 
Remove the domain from the list immediately !!!!!

**Comment by iam-py-test** [comment] 2023-12-17 15:44
Duplicate of https://github.com/RPiList/specials/issues/1382.
Spamming new issues will not make @RPiList respond quicker, and it is generally considered rude. #1382 was opened only 3 hours ago; @RPiList could be busy.
Thank you.

**Comment by ipv64net** [comment] 2023-12-17 15:52
This is the second time the domain has been on this list. Slowly but surely, this could be declared as damage to business. Should hurry up

**Comment by iam-py-test** [comment] 2023-12-17 16:26
With all due respect, @RPiList is a volunteer; they can not dedicate all their time to this project, and it is unreasonable to expect an instant response. As I said, opening a new issue does not 
> This is the second time the domain has been on this list.

Mistakes happen. I understand it is inconvenient, and I sympathize, but mistakes do happen.
> this could be declared as damage to business

With all due respect, I fail to see how two false positives are "damage to business".
Additionally, if I read your comment correctly, threatening legal action is rude and never ([well, almost never](https://github.com/easylist/easylist/commit/a4d380ad1a3b33a0fab679a1a8c5a791321622b3)) effective at changing the minds of filterlist maintainers. I am not a lawyer, but that argument stands on very shaky legal ground.

Thank you.

**Comment by RPiList** [comment] 2023-12-17 17:34
> It's getting on my nerves. "schroederdennis.de" is not malware... Remove the domain from the list immediately !!!!!

You might want to take this fight to urlhaus.abuse.ch.

They claim you were distributing malware.

Check out: https://urlhaus.abuse.ch/url/2723008

**Comment by iam-py-test** [comment] 2023-12-17 17:36
@RPiList that URL has been taken down and returns 404:
> While the URL referenced below may have been used by bad actors to spread malware, the URL seems to be clean for a long time. Hence the the URL / website should no longer represent a threat. As a result, URLhaus considers this record as historical. This database entry has not impact on the reputation of the website / domain nor does it appear in any of our blocklists anymore.

Thanks

**Comment by RPiList** [comment] 2023-12-17 18:11
> @RPiList that URL has been taken down and returns 404:

Ja. Da es nicht unüblich ist, dass Schadware vorübergehend offline genommen wird; um wieder ein Whitelisting zu erreichen, wird die Domain bei URLhaus 90 Tage weiter geführt. 

Insoweit können wir diese einzelne Domain bei uns löschen. Bei URLhaus wird sie trotzdem weiter geführt, bis zum Ablauf der 90-Tage-Frist.

Wir haben die Domain jetzt erst mal auf der Whitelist. Kann also nicht mehr bei uns aufkreuzen. Aber so richtig happy bin ich damit auch nicht. Weil lt. eigener Aussage wirklich mal Schadware verteilt wurde. Wenn das wieder passiert und wir die Domain jetzt whitelisten... dann sind unsere Nutzer angeschissen...

**Closed** 2023-12-18 23:59 UTC
